Jul 12 12:11:08 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:11:08 vps systemd[717016]: divinebot.service: Failed to locate executable /home/dilshod/DivineBot/venv/bin/python3: No such file or directory
Jul 12 12:11:08 vps systemd[717016]: [0;1;31m[0;1;39m[0;1;31mdivinebot.service: Failed at step EXEC spawning /home/dilshod/DivineBot/venv/bin/python3: No such file or directory[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=203/EXEC[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:08 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 1.
Jul 12 12:11:08 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:11:08 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:11:08 vps systemd[717018]: divinebot.service: Failed to locate executable /home/dilshod/DivineBot/venv/bin/python3: No such file or directory
Jul 12 12:11:08 vps systemd[717018]: [0;1;31m[0;1;39m[0;1;31mdivinebot.service: Failed at step EXEC spawning /home/dilshod/DivineBot/venv/bin/python3: No such file or directory[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=203/EXEC[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:08 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 2.
Jul 12 12:11:08 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:11:08 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:11:08 vps systemd[717019]: divinebot.service: Failed to locate executable /home/dilshod/DivineBot/venv/bin/python3: No such file or directory
Jul 12 12:11:08 vps systemd[717019]: [0;1;31m[0;1;39m[0;1;31mdivinebot.service: Failed at step EXEC spawning /home/dilshod/DivineBot/venv/bin/python3: No such file or directory[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=203/EXEC[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:08 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 3.
Jul 12 12:11:08 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:11:08 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:11:08 vps systemd[717020]: divinebot.service: Failed to locate executable /home/dilshod/DivineBot/venv/bin/python3: No such file or directory
Jul 12 12:11:08 vps systemd[717020]: [0;1;31m[0;1;39m[0;1;31mdivinebot.service: Failed at step EXEC spawning /home/dilshod/DivineBot/venv/bin/python3: No such file or directory[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=203/EXEC[0m
Jul 12 12:11:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:09 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 4.
Jul 12 12:11:09 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:11:09 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:11:09 vps systemd[717022]: divinebot.service: Failed to locate executable /home/dilshod/DivineBot/venv/bin/python3: No such file or directory
Jul 12 12:11:09 vps systemd[717022]: [0;1;31m[0;1;39m[0;1;31mdivinebot.service: Failed at step EXEC spawning /home/dilshod/DivineBot/venv/bin/python3: No such file or directory[0m
Jul 12 12:11:09 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=203/EXEC[0m
Jul 12 12:11:09 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:09 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 5.
Jul 12 12:11:09 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:11:09 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Start request repeated too quickly.[0m
Jul 12 12:11:09 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:11:09 vps systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start Divine Bot Service.[0m
Jul 12 12:23:00 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:23:00 vps python3[717151]: 2023-07-12 12:23:00.396214
Jul 12 12:23:00 vps python3[717151]: Traceback (most recent call last):
Jul 12 12:23:00 vps python3[717151]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:23:00 vps python3[717151]:     import handlers
Jul 12 12:23:00 vps python3[717151]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:23:00 vps python3[717151]:     from .authorization import *
Jul 12 12:23:00 vps python3[717151]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:23:00 vps python3[717151]:     from .login import *
Jul 12 12:23:00 vps python3[717151]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:23:00 vps python3[717151]:     from dispatch import dp
Jul 12 12:23:00 vps python3[717151]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:23:00 vps python3[717151]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:23:00 vps python3[717151]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:23:00 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:23:00 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:01 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 1.
Jul 12 12:23:01 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:23:01 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:23:01 vps python3[717153]: 2023-07-12 12:23:01.451607
Jul 12 12:23:01 vps python3[717153]: Traceback (most recent call last):
Jul 12 12:23:01 vps python3[717153]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:23:01 vps python3[717153]:     import handlers
Jul 12 12:23:01 vps python3[717153]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:23:01 vps python3[717153]:     from .authorization import *
Jul 12 12:23:01 vps python3[717153]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:23:01 vps python3[717153]:     from .login import *
Jul 12 12:23:01 vps python3[717153]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:23:01 vps python3[717153]:     from dispatch import dp
Jul 12 12:23:01 vps python3[717153]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:23:01 vps python3[717153]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:23:01 vps python3[717153]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:23:01 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:23:01 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:02 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 2.
Jul 12 12:23:02 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:23:02 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:23:02 vps python3[717155]: 2023-07-12 12:23:02.460651
Jul 12 12:23:02 vps python3[717155]: Traceback (most recent call last):
Jul 12 12:23:02 vps python3[717155]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:23:02 vps python3[717155]:     import handlers
Jul 12 12:23:02 vps python3[717155]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:23:02 vps python3[717155]:     from .authorization import *
Jul 12 12:23:02 vps python3[717155]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:23:02 vps python3[717155]:     from .login import *
Jul 12 12:23:02 vps python3[717155]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:23:02 vps python3[717155]:     from dispatch import dp
Jul 12 12:23:02 vps python3[717155]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:23:02 vps python3[717155]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:23:02 vps python3[717155]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:23:03 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:23:03 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:03 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 3.
Jul 12 12:23:03 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:23:03 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:23:03 vps python3[717157]: 2023-07-12 12:23:03.458908
Jul 12 12:23:03 vps python3[717157]: Traceback (most recent call last):
Jul 12 12:23:03 vps python3[717157]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:23:03 vps python3[717157]:     import handlers
Jul 12 12:23:03 vps python3[717157]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:23:03 vps python3[717157]:     from .authorization import *
Jul 12 12:23:03 vps python3[717157]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:23:03 vps python3[717157]:     from .login import *
Jul 12 12:23:03 vps python3[717157]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:23:03 vps python3[717157]:     from dispatch import dp
Jul 12 12:23:03 vps python3[717157]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:23:03 vps python3[717157]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:23:03 vps python3[717157]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:23:04 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:23:04 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:04 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 4.
Jul 12 12:23:04 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:23:04 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:23:04 vps python3[717159]: 2023-07-12 12:23:04.458290
Jul 12 12:23:04 vps python3[717159]: Traceback (most recent call last):
Jul 12 12:23:04 vps python3[717159]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:23:04 vps python3[717159]:     import handlers
Jul 12 12:23:04 vps python3[717159]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:23:04 vps python3[717159]:     from .authorization import *
Jul 12 12:23:04 vps python3[717159]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:23:04 vps python3[717159]:     from .login import *
Jul 12 12:23:04 vps python3[717159]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:23:04 vps python3[717159]:     from dispatch import dp
Jul 12 12:23:04 vps python3[717159]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:23:04 vps python3[717159]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:23:04 vps python3[717159]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:23:04 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:23:04 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:05 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 5.
Jul 12 12:23:05 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:23:05 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Start request repeated too quickly.[0m
Jul 12 12:23:05 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:05 vps systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start Divine Bot Service.[0m
Jul 12 12:23:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Start request repeated too quickly.[0m
Jul 12 12:23:08 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:23:08 vps systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start Divine Bot Service.[0m
Jul 12 12:30:11 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:30:12 vps python3[717229]: 2023-07-12 12:30:11.844974
Jul 12 12:30:12 vps python3[717229]: Traceback (most recent call last):
Jul 12 12:30:12 vps python3[717229]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:30:12 vps python3[717229]:     import handlers
Jul 12 12:30:12 vps python3[717229]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:30:12 vps python3[717229]:     from .authorization import *
Jul 12 12:30:12 vps python3[717229]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:30:12 vps python3[717229]:     from .login import *
Jul 12 12:30:12 vps python3[717229]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:30:12 vps python3[717229]:     from dispatch import dp
Jul 12 12:30:12 vps python3[717229]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:30:12 vps python3[717229]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:30:12 vps python3[717229]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:30:12 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:30:12 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:12 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 1.
Jul 12 12:30:12 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:30:12 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:30:13 vps python3[717231]: 2023-07-12 12:30:12.701769
Jul 12 12:30:13 vps python3[717231]: Traceback (most recent call last):
Jul 12 12:30:13 vps python3[717231]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:30:13 vps python3[717231]:     import handlers
Jul 12 12:30:13 vps python3[717231]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:30:13 vps python3[717231]:     from .authorization import *
Jul 12 12:30:13 vps python3[717231]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:30:13 vps python3[717231]:     from .login import *
Jul 12 12:30:13 vps python3[717231]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:30:13 vps python3[717231]:     from dispatch import dp
Jul 12 12:30:13 vps python3[717231]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:30:13 vps python3[717231]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:30:13 vps python3[717231]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:30:13 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:30:13 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:13 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 2.
Jul 12 12:30:13 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:30:13 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:30:14 vps python3[717233]: 2023-07-12 12:30:13.703130
Jul 12 12:30:14 vps python3[717233]: Traceback (most recent call last):
Jul 12 12:30:14 vps python3[717233]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:30:14 vps python3[717233]:     import handlers
Jul 12 12:30:14 vps python3[717233]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:30:14 vps python3[717233]:     from .authorization import *
Jul 12 12:30:14 vps python3[717233]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:30:14 vps python3[717233]:     from .login import *
Jul 12 12:30:14 vps python3[717233]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:30:14 vps python3[717233]:     from dispatch import dp
Jul 12 12:30:14 vps python3[717233]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:30:14 vps python3[717233]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:30:14 vps python3[717233]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:30:14 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:30:14 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:14 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 3.
Jul 12 12:30:14 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:30:14 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:30:15 vps python3[717235]: 2023-07-12 12:30:14.674230
Jul 12 12:30:15 vps python3[717235]: Traceback (most recent call last):
Jul 12 12:30:15 vps python3[717235]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:30:15 vps python3[717235]:     import handlers
Jul 12 12:30:15 vps python3[717235]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:30:15 vps python3[717235]:     from .authorization import *
Jul 12 12:30:15 vps python3[717235]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:30:15 vps python3[717235]:     from .login import *
Jul 12 12:30:15 vps python3[717235]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:30:15 vps python3[717235]:     from dispatch import dp
Jul 12 12:30:15 vps python3[717235]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:30:15 vps python3[717235]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:30:15 vps python3[717235]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:30:15 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:30:15 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:15 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 4.
Jul 12 12:30:15 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:30:15 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:30:15 vps python3[717236]: 2023-07-12 12:30:15.415620
Jul 12 12:30:15 vps python3[717236]: Traceback (most recent call last):
Jul 12 12:30:15 vps python3[717236]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:30:15 vps python3[717236]:     import handlers
Jul 12 12:30:15 vps python3[717236]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 3, in <module>
Jul 12 12:30:15 vps python3[717236]:     from .authorization import *
Jul 12 12:30:15 vps python3[717236]:   File "/home/dilshod/DivineBot/handlers/authorization/__init__.py", line 1, in <module>
Jul 12 12:30:15 vps python3[717236]:     from .login import *
Jul 12 12:30:15 vps python3[717236]:   File "/home/dilshod/DivineBot/handlers/authorization/login.py", line 9, in <module>
Jul 12 12:30:15 vps python3[717236]:     from dispatch import dp
Jul 12 12:30:15 vps python3[717236]:   File "/home/dilshod/DivineBot/dispatch.py", line 4, in <module>
Jul 12 12:30:15 vps python3[717236]:     from configs.constants import BOT_TOKEN, STORAGE_PATH
Jul 12 12:30:15 vps python3[717236]: ImportError: cannot import name 'STORAGE_PATH' from 'configs.constants' (/home/dilshod/DivineBot/configs/constants.py)
Jul 12 12:30:15 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:30:15 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:16 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 5.
Jul 12 12:30:16 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:30:16 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Start request repeated too quickly.[0m
Jul 12 12:30:16 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:30:16 vps systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start Divine Bot Service.[0m
Jul 12 12:36:39 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:36:40 vps python3[717267]: 2023-07-12 12:36:39.245498
Jul 12 12:36:40 vps python3[717267]: ('2023-07-12 9:00:00.000000+05:00', '2023-07-12 9:20:00.000000+05:00')
Jul 12 12:36:40 vps python3[717267]: 2023-07-12
Jul 12 12:36:40 vps python3[717267]: 12:36:40
Jul 12 12:36:40 vps python3[717267]: Traceback (most recent call last):
Jul 12 12:36:40 vps python3[717267]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:36:40 vps python3[717267]:     import handlers
Jul 12 12:36:40 vps python3[717267]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 5, in <module>
Jul 12 12:36:40 vps python3[717267]:     from .agent import *
Jul 12 12:36:40 vps python3[717267]:   File "/home/dilshod/DivineBot/handlers/agent/__init__.py", line 1, in <module>
Jul 12 12:36:40 vps python3[717267]:     from .vizit import *
Jul 12 12:36:40 vps python3[717267]:   File "/home/dilshod/DivineBot/handlers/agent/vizit.py", line 4, in <module>
Jul 12 12:36:40 vps python3[717267]:     import RO as ro
Jul 12 12:36:40 vps python3[717267]: ModuleNotFoundError: No module named 'RO'
Jul 12 12:36:40 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:36:40 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:40 vps systemd[1]: divinebot.service: Consumed 1.355s CPU time.
Jul 12 12:36:40 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 1.
Jul 12 12:36:40 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:36:40 vps systemd[1]: divinebot.service: Consumed 1.355s CPU time.
Jul 12 12:36:40 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:36:41 vps python3[717271]: 2023-07-12 12:36:40.690716
Jul 12 12:36:41 vps python3[717271]: ('2023-07-12 9:00:00.000000+05:00', '2023-07-12 9:20:00.000000+05:00')
Jul 12 12:36:41 vps python3[717271]: 2023-07-12
Jul 12 12:36:41 vps python3[717271]: 12:36:41
Jul 12 12:36:41 vps python3[717271]: Traceback (most recent call last):
Jul 12 12:36:41 vps python3[717271]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:36:41 vps python3[717271]:     import handlers
Jul 12 12:36:41 vps python3[717271]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 5, in <module>
Jul 12 12:36:41 vps python3[717271]:     from .agent import *
Jul 12 12:36:41 vps python3[717271]:   File "/home/dilshod/DivineBot/handlers/agent/__init__.py", line 1, in <module>
Jul 12 12:36:41 vps python3[717271]:     from .vizit import *
Jul 12 12:36:41 vps python3[717271]:   File "/home/dilshod/DivineBot/handlers/agent/vizit.py", line 4, in <module>
Jul 12 12:36:41 vps python3[717271]:     import RO as ro
Jul 12 12:36:41 vps python3[717271]: ModuleNotFoundError: No module named 'RO'
Jul 12 12:36:41 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:36:41 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:41 vps systemd[1]: divinebot.service: Consumed 1.148s CPU time.
Jul 12 12:36:41 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 2.
Jul 12 12:36:41 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:36:41 vps systemd[1]: divinebot.service: Consumed 1.148s CPU time.
Jul 12 12:36:41 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:36:42 vps python3[717273]: 2023-07-12 12:36:41.916832
Jul 12 12:36:42 vps python3[717273]: ('2023-07-12 9:00:00.000000+05:00', '2023-07-12 9:20:00.000000+05:00')
Jul 12 12:36:42 vps python3[717273]: 2023-07-12
Jul 12 12:36:42 vps python3[717273]: 12:36:42
Jul 12 12:36:42 vps python3[717273]: Traceback (most recent call last):
Jul 12 12:36:42 vps python3[717273]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:36:42 vps python3[717273]:     import handlers
Jul 12 12:36:42 vps python3[717273]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 5, in <module>
Jul 12 12:36:42 vps python3[717273]:     from .agent import *
Jul 12 12:36:42 vps python3[717273]:   File "/home/dilshod/DivineBot/handlers/agent/__init__.py", line 1, in <module>
Jul 12 12:36:42 vps python3[717273]:     from .vizit import *
Jul 12 12:36:42 vps python3[717273]:   File "/home/dilshod/DivineBot/handlers/agent/vizit.py", line 4, in <module>
Jul 12 12:36:42 vps python3[717273]:     import RO as ro
Jul 12 12:36:42 vps python3[717273]: ModuleNotFoundError: No module named 'RO'
Jul 12 12:36:42 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:36:42 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:42 vps systemd[1]: divinebot.service: Consumed 1.167s CPU time.
Jul 12 12:36:42 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 3.
Jul 12 12:36:42 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:36:42 vps systemd[1]: divinebot.service: Consumed 1.167s CPU time.
Jul 12 12:36:42 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:36:43 vps python3[717275]: 2023-07-12 12:36:43.205067
Jul 12 12:36:43 vps python3[717275]: ('2023-07-12 9:00:00.000000+05:00', '2023-07-12 9:20:00.000000+05:00')
Jul 12 12:36:43 vps python3[717275]: 2023-07-12
Jul 12 12:36:43 vps python3[717275]: 12:36:43
Jul 12 12:36:43 vps python3[717275]: Traceback (most recent call last):
Jul 12 12:36:43 vps python3[717275]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:36:43 vps python3[717275]:     import handlers
Jul 12 12:36:43 vps python3[717275]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 5, in <module>
Jul 12 12:36:43 vps python3[717275]:     from .agent import *
Jul 12 12:36:43 vps python3[717275]:   File "/home/dilshod/DivineBot/handlers/agent/__init__.py", line 1, in <module>
Jul 12 12:36:43 vps python3[717275]:     from .vizit import *
Jul 12 12:36:43 vps python3[717275]:   File "/home/dilshod/DivineBot/handlers/agent/vizit.py", line 4, in <module>
Jul 12 12:36:43 vps python3[717275]:     import RO as ro
Jul 12 12:36:43 vps python3[717275]: ModuleNotFoundError: No module named 'RO'
Jul 12 12:36:44 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:36:44 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:44 vps systemd[1]: divinebot.service: Consumed 1.149s CPU time.
Jul 12 12:36:44 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 4.
Jul 12 12:36:44 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:36:44 vps systemd[1]: divinebot.service: Consumed 1.149s CPU time.
Jul 12 12:36:44 vps systemd[1]: Started Divine Bot Service.
Jul 12 12:36:45 vps python3[717277]: 2023-07-12 12:36:44.414373
Jul 12 12:36:45 vps python3[717277]: ('2023-07-12 9:00:00.000000+05:00', '2023-07-12 9:20:00.000000+05:00')
Jul 12 12:36:45 vps python3[717277]: 2023-07-12
Jul 12 12:36:45 vps python3[717277]: 12:36:45
Jul 12 12:36:45 vps python3[717277]: Traceback (most recent call last):
Jul 12 12:36:45 vps python3[717277]:   File "/home/dilshod/DivineBot/run.py", line 3, in <module>
Jul 12 12:36:45 vps python3[717277]:     import handlers
Jul 12 12:36:45 vps python3[717277]:   File "/home/dilshod/DivineBot/handlers/__init__.py", line 5, in <module>
Jul 12 12:36:45 vps python3[717277]:     from .agent import *
Jul 12 12:36:45 vps python3[717277]:   File "/home/dilshod/DivineBot/handlers/agent/__init__.py", line 1, in <module>
Jul 12 12:36:45 vps python3[717277]:     from .vizit import *
Jul 12 12:36:45 vps python3[717277]:   File "/home/dilshod/DivineBot/handlers/agent/vizit.py", line 4, in <module>
Jul 12 12:36:45 vps python3[717277]:     import RO as ro
Jul 12 12:36:45 vps python3[717277]: ModuleNotFoundError: No module named 'RO'
Jul 12 12:36:45 vps systemd[1]: [0;1;39m[0;1;31m[0;1;39mdivinebot.service: Main process exited, code=exited, status=1/FAILURE[0m
Jul 12 12:36:45 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:45 vps systemd[1]: divinebot.service: Consumed 1.048s CPU time.
Jul 12 12:36:45 vps systemd[1]: divinebot.service: Scheduled restart job, restart counter is at 5.
Jul 12 12:36:45 vps systemd[1]: Stopped Divine Bot Service.
Jul 12 12:36:45 vps systemd[1]: divinebot.service: Consumed 1.048s CPU time.
Jul 12 12:36:45 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Start request repeated too quickly.[0m
Jul 12 12:36:45 vps systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mdivinebot.service: Failed with result 'exit-code'.[0m
Jul 12 12:36:45 vps systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start Divine Bot Service.[0m
